---
name: Codespell

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.codespellrc'
      - '.github/workflows/codespell.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.codespellrc'
      - '.github/workflows/codespell.yml'

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
